/*
 * This file was automatically generated by EvoSuite
 * Wed Sep 06 20:18:38 GMT 2017
 */

package org.araguacaima.commons.exception.core;

import org.junit.Test;
import static org.junit.Assert.*;
import org.araguacaima.commons.exception.core.ApplicationException;
import org.araguacaima.commons.exception.core.Severity;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ApplicationException_ESTest extends ApplicationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Severity severity0 = Severity.FATAL;
      ApplicationException applicationException0 = new ApplicationException("}", severity0);
      assertEquals("}", applicationException0.getKeyCode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Severity severity0 = Severity.FATAL;
      ApplicationException applicationException0 = new ApplicationException("", severity0, (Object) "");
      assertEquals("", applicationException0.getExtendedMessage());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Severity severity0 = Severity.INFO;
      ApplicationException applicationException0 = new ApplicationException("c4/_[:y|Icojk3m", severity0, "c4/_[:y|Icojk3m");
      ApplicationException applicationException1 = new ApplicationException("c4/_[:y|Icojk3m", applicationException0);
      assertEquals("c4/_[:y|Icojk3m", applicationException1.getKeyCode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Severity severity0 = Severity.FATAL;
      Object object0 = new Object();
      ApplicationException applicationException0 = new ApplicationException("%Xb82}G^Z8'wv,2", severity0, (String) null, object0);
      Throwable[] throwableArray0 = applicationException0.getSuppressed();
      ApplicationException applicationException1 = new ApplicationException("zO", severity0, (Object[]) throwableArray0);
      assertEquals("zO", applicationException1.getKeyCode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ApplicationException applicationException0 = new ApplicationException("f|@lAq2");
      assertEquals("", applicationException0.getExtendedMessage());
  }
}
